apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: recut
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: recut
  name: recut-serving-cert
spec:
  dnsNames:
  - recut-webhook-service.{{.Release.Namespace}}.svc
  - recut-webhook-service.{{.Release.Namespace}}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: recut-selfsigned-issuer
  secretName: webhook-server-cert
