apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: recut
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: recut
  name: recut-serving-cert
  namespace: recut
spec:
  dnsNames:
  - recut-webhook-service.recut.svc
  - recut-webhook-service.recut.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: recut-selfsigned-issuer
  secretName: webhook-server-cert
