apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: recut-podscrape
spec:
  jobLabel: recut-podscrape
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      control-plane: controller-manager
      controller: recut
