apiVersion: v1
data:
  ANNOTATION_DOMAIN: {{ .Values.env.ANNOTATION_DOMAIN | b64enc }}
  # cpu is in mCPUs
  CPU_REQUEST_MIN: {{ .Values.env.CPU_REQUEST_MIN | b64enc }}
  ISTIO_PROXY_CPU_MIN: {{ .Values.env.ISTIO_PROXY_CPU_MIN | b64enc }}
  # mem is in Megabytes
  MEMORY_LIMIT_MIN: {{ .Values.env.MEMORY_LIMIT_MIN | b64enc }}
  ISTIO_MEMORY_LIMIT_MIN: {{ .Values.env.ISTIO_MEMORY_LIMIT_MIN | b64enc }}
  MEMORY_REQUEST_MIN: {{ .Values.env.MEMORY_REQUEST_MIN | b64enc }}
kind: Secret
metadata:
  name: recut-config
type: Opaque
