apiVersion: v1
data:
  ANNOTATION_DOMAIN: {{ .Values.env.ANNOTATION_DOMAIN | b64enc }}
  CPU_REQUEST_MIN: {{ .Values.env.CPU_REQUEST_MIN | b64enc }}
  ISTIO_PROXY_CPU_MIN: {{ .Values.env.ISTIO_PROXY_CPU_MIN | b64enc }}
kind: Secret
metadata:
  name: recut-config
  namespace: recut
type: Opaque
