apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: recut
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: recut
  name: recut-controller-manager
